### PR TITLE
Move logo from repository

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by kevva** [comment]
Why?

**Comment by vinkla** [comment]
To reduce space https://vinkla.com/posts/upload-images-github/

Not sure how does NPM handles this kind of content? Does it download the entire repo during install?

**Comment by kevva** [comment]
The image is not that large and it should really be under source control anyway. How else would you track changes to it? Besides that, it's good if people want to improve upon it or likewise.

npm only downloads the files defined in the `files` propery in `package.json`.

I'm :-1: on this.

**Comment by sindresorhus** [comment]
:-1: 

> To reduce space https://vinkla.com/posts/upload-images-github/

Then you lose history on the image and I personally want the image to be visible in the readme even if offline.

> Does it download the entire repo when you run npm install?

No.

**Comment by vinkla** [comment]
I guess this wont be a problem if you don't actually download the file when installing this package.

**Pull request closed without merging**
